# Compose schema version
version: '3.3'

# Overriding requirements
services:
  client:
    build:
      args:
        REQUIREMENTS: examples/traffic/requirements.txt
    deploy:
      replicas: 2
    volumes:
      - ${HOST_REPO_DIR:-.}/fedn:/app/fedn
      - ${HOST_REPO_DIR:-.}/examples/traffic/data:/var/data
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
            reducer: 193.40.155.17
            combiner: 193.40.155.17
